task_tag: gripper_task
data:
  data_path: "/home/aryan/IL_Workspace/data_collection_output"  # Update this to the actual path of your JSON files
  # for your loader: exactly the YAML‑filenames (no nested lists)
  keys_traj:
    names:
        - gripper_pressure
        - joint_states_fixed
        - force_torque_sensor_broadcaster_wrench
        - servo_node_delta_twist_cmds
    specs:
      - [gripper_pressure, gripper_pressure, null, null]
      - [actions_cleaned,  servo_node_delta_twist_cmds, null, null]
      - [joint_states_fixed, joint_states_fixed, null, null]   # 24-D (pos+vel+eff)
      - ['force_torque_sensor_broadcaster_wrench', 'force_torque_sensor_broadcaster_wrench', null, null]


  preloaded: false
  num_worker: 0

  # ── these four used by your CustomSequenceTrainValTest split ──
  test_fraction:      0.1
  val_fraction:       0.1
  window_size_train: 5
  window_size_test:   5

  # ── padding for your sequence slices ──
  pad_before: false
  pad_after:  true
  pad_type:   near

  joint_states_stride: 10    # only take every 10th record
  device: ${algo_cfg.algo_cfg.device}  # Add device to inherit from algo_cfg


target_dims:
  actions: 6  # or 7, depending on your action dimensions

env:
  _target_: srl_il.simulators.robomimic.RobomimicEnv
  env_name: PickPlaceCan
  env_type: 1
  obs_name_mapping: []  # No image-based observations
  env_kwargs:
    has_renderer: false
    has_offscreen_renderer: true
    ignore_done: true
    use_object_obs: true
    use_camera_obs: false  # Set to false since you're not using cameras
    control_freq: 20
    controller_configs: 
      type: "OSC_POSE"
      input_max: 1
      input_min: -1
      output_max: [0.05,0.05,0.05,0.5,0.5,0.5]
      output_min: [-0.05,-0.05,-0.05,-0.5,-0.5,-0.5]
      kp: 150
      damping: 1
      impedance_mode: "fixed"
      kp_limits: [0,300]
      damping_limits: [0,10]
      position_limits: null
      orientation_limits: null
      uncouple_pos_ori: true
      control_delta: false  # Set to false as per your script

train:
  rollout_horizon: 300
  num_epochs: 80